# Generated by Django 2.1.1 on 2018-09-11 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0002_auto_20180911_2052'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name_plural': '财务表'},
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='photo',
            new_name='phone',
        ),
    ]
